#+title: Automatic Updates
#+date: 2023-05-01
#+draft: true
#+tags[]: notags

* Automatic Updates

*How the indexes here are automatically updated when a new article is published.*

The indexes on this site are updated every time a new article is published, not by hand but through the use of scripts. This allows new albums and musicians to be added to the Albums Index, Musicians Index, and Timeline pages automatically with no manual editing. These indexes are generated using data that is normalized and canonical, such as proper and consistent musician names, album titles, and corresponding data such as musician websites, album labels, years, performing musicians, ...

Overview of the automatic process (scripted):
- Maintain the existing content in each index
- Add new entries (albums, musicians) into the proper places in each index
- Republish

All I need to do is write the articles, add some minimal data (ids, text) to a few properties, and run a script.

** How is this done?

All the articles are written outside the newsletter platform (Substack). They are written and saved as text files (Org format) using Emacs.

When an article is ready to be published, it is exported to html format (via Emacs), and copied and pasted into the Substack editor (by hand, as Substack offers no API), together with images and media files. One major benefit of this is that my writing and configuration is not located primarily in, or owned by, any one online platform or service. The latest version of each article is always saved in a text file (the authoritative source of truth) that I own and manage with complete freedom, and this includes the complete version history of changes to each file. (Using git for version history, this includes the convenience and reassurance of being able to write, revise, and edit on a local machine (online or offline) with a simple way to branch, commit, revert, and compare recent changes or differences between any changes in the history.)

Included in the file format are a few standard Org properties, set for each article, whose values are special strings:
- =:id:= unique id for an article: artist-name-album-title (:id: should really be :slug:, or the filename)
- =:published:= date the article was published: yyyy-mm-dd
- =:members:= list of ids of the musicians for this article (album): member-one member-two member-three=\"guitar (track #5)\" member-four *(Used in 'albums' articles, which is most of them.)*

** The process

Using the values from all the published articles, and the list of members (ids), indexes can be generated automatically through scripts (mostly python, with lisp for org->md/source->hugo, and some bash scripts)o and centralized csv files.

The csv files are used to store additional data (albums data, musicians data: items are identified by unique keys based on names) in a convenient format. It also helps to keep the Org files shorter, without lots of lines in the =:PROPERTIES:= drawer for each node. It is possible and arguably simpler to just use the Org files to store all the data together with their content (per node), but using a supporting csv file as a datastore is fine, at least for now.

Overview of the automatic process (scripted):

1. When a new article is published, the indexes are regenerated by calling a command line script.
2. The output is written to the =<username>.github.io= repository, committed, and pushed to GitHub.
3. The push to GitHub triggers an automatic action (=.github/workflows/<filename>.yml=) that builds and republishes this site.

This is how the indexes on this site are automatically updated.

** Destination

These indexes are served through a =<username>.github.io= repo where the settings were updated to use a custom subdomain.

This is the same custom domain used to serve the newsletter archive =<domain>.com= and =www.<domain>.com= (served by Substack), but using the subdomain name =docs= (served by GitHub). The name of the subdomain could be anything that makes sense.
