#+title: Started previews
#+date: 2022-09-21
#+draft: false
#+tags[]: versions

* September 2022

I still had a long list of albums that I wanted to introduce, but not enough time to write text for each that I would be satisfied with. I decided to release articles with the label “Preview”. These would be very similar to the regular album articles I had been posting, with images of the albums and audio excerpts for each, but without any descriptive comments written about the album or musicians. I planned to release Previews in quick succession to the website so that I would have something out there for an older batch of albums. Once posted, these Previews would serve as temporary placeholders that I could come back to and extend later, but would at least share images and audio.

In September 2022, I started releasing Preview articles. I added 53 Preview articles from September 21, 2022 through January 23, 2023.

In January 2023, I moved the project back to Substack by importing all the Markdown files that I had created up to this point.
