#+title: Jekyll to Hugo migration
#+date: 2025-03-11
#+draft: true
#+tags[]: notags

* March 2025

Jekyll had become too slow, when writing and changing Markdown files on my laptop. With hundreds of articles (albums, clubs, guides), and thousands of supplemental files (images, audio, and data files), the reloading of the site when a file changes had become unbearably slow. Each page change required around 60 to 120 seconds each time a page changed. This turns out to be a common frustration with Jekyll and large sites.

Testing Hugo with my existing Markdown content turned out to be incredibly fast, on the other of ~100 milliseconds to reload. Since Hugo works with markdown, it was easy to test it out after making minor syntax changes.

Things that needed to change to move from a Jekyll- to a Hugo-based solution:

- Markdown files: Minor syntax changes, file directory changes, page bundles
- Configuration: From =_config.yml= to =hugo.toml=
- Theme changes: Pick a basic Hugo theme and customize pages to match what I had in my Jekyll theme.
- Pages need to contain a similar version as before, to copy and paste to Substack
- Publish History page
- Generated pages: Unified Index, Albums Index, Musicians Index (with cross-references to albums), Clubs Index, Audio Mixes
- A dashboard to show all pages with statistics, comments, and related info

From the reader’s perspective, nothing noticeably changed, and the newsletter and archive were still on Substack.

Guides/references:
- https://www.sarasoueidan.com/blog/jekyll-ghpages-to-hugo-netlify/
- https://chenhuijing.com/blog/migrating-from-jekyll-to-hugo/



* Details

* March 2025: Hugo Migration

** Work Involved
   - Start a branch =hugo-migrate= on jazzofjapan repo.
   - Checkout a separate clone of jazzofjapan (=jazzofjapan-jekyll=) for comparing and testing (run both servers in parallel)
   - Update =jazzofjapan-java= to generate new *.json files for data usable by hugo (yaml would also be ok)
      - This makes =ArticleStatus= (or whatever replaces it) to be an essential part of the build, each time data (clubs, musicians, article-status, etc) changes.

** Drawbacks

** Jekyll artfacts removed from code

- =_config.yml=
- =404.html=
- =/collections=

** SETUP

- after git clone, update the theme:
   - =git submodule update --init --recursive=

** NOTES

- [v4.1] 2025 March: "Jazz of Japan"
  - converted dev backend from jekyll to hugo
  - production is unchanged (Substack)

- Last git commit id for working jekyll site:

#+BEGIN_EXAMPLE
- commit a57da32620c4581fb8c407371c792fbc25d19c2a (origin/master, origin/HEAD, master)
| Author: Brian McCrory <brianmccrory@outlook.com>
| Date:   Sun Mar 2 09:15:24 2025 +0900
|
|     fix infinite loop uncovered by removing Updated line in publish history
#+END_EXAMPLE


Some random refs:
   - https://chenhuijing.com/blog/migrating-from-jekyll-to-hugo/

#+BEGIN_EXAMPLE

WARN  Raw HTML omitted while rendering "C:/Users/brian/git/jazzofjapan/content/guides/ten-top-10s-for-live-jazz-in-tokyo.md"; see https://gohugo.io/getting-started/configuration-markup/#rendererunsafe

#+END_EXAMPLE

** OLD/NEW

Posts (debug and overall listing latest to oldest):
- OLD http://localhost:4000/posts
- NEW http://localhost:1313/posts/

Unified Index:
- OLD http://localhost:4000/unified-index
- NEW http://localhost:1313/unified/

Publish History
- OLD 1 http://localhost:4000/publish-history-timeline
- OLD 2 http://localhost:4000/resources-publish-history
- NEW http://localhost:1313/timeline/

Albums:
- OLD http://localhost:4000/albums/
- NEW http://localhost:1313/albums/

Musicians:
- OLD http://localhost:4000/musicians/
- NEW http://localhost:1313/musicians/

Clubs:
- OLD http://localhost:4000/clubs/
- NEW http://localhost:1313/clubs/

Guides:
- OLD http://localhost:4000/guides
- NEW http://localhost:1313/guides/

Mixes:
- OLD http://localhost:4000/mixes
- NEW http://localhost:1313/audio-mixes/

Audio-Mixes (generate templates and commands for compilation*.mp3):
- OLD http://localhost:4000/audio
- NEW Generation/updating of audio-mix-*.md files by AudioMixes.java

About
- OLD http://localhost:4000/about
- NEW http://localhost:1313/general/about/

Tests (generated by ArticleStatus.java):
   - =resources-publish-history.md= -> =content/tests/timeline.md=

REMOVED AND NOT REPLACED (at least initially): (each corresponds to a *.md file)
- http://localhost:4000/albums-artist # list of album covers ordered by artist
- http://localhost:4000/albums-default # list of album covers, like an instagram feed
- http://localhost:4000/albums-list # text list of albums
- http://localhost:4000/albums-published # ???
- http://localhost:4000/albums-year.html # list of album covers ordered by album year
- http://localhost:4000/batches/ # albums listed by 'batch' identifiers, such as trip38, trip 37, ...
- http://localhost:4000/captions # list of image captions
- http://localhost:4000/copyright
- http://localhost:4000/index # homepage
- http://localhost:4000/premium-index
- http://localhost:4000/reposts/
- http://localhost:4000/search.html
- http://localhost:4000/sitemap.xml # may use hugo's sitemap functionality at some point
- http://localhost:4000/p/master-index # was basically the same as unified-index


REMOVED FILES:
- browserconfig.xml
- Gemfile
- Gemfile.lock
- search.json
- assets/js/search-script.js
- assets/main.scss
- _layouts/*.html # replaced by /layouts/* dirs and files
- _includes/*.md (and *.html) # hugo uses layouts/partials/

TO DO: (GENERATED FILES USED AS DIFF COMPARISONS):
- resources-albums-index.md
- resources-clubs-index.md
- resources-guides-index.md
- resources-mixes-index.md
- resources-musicians-index.md
- resources-publish-history.md
- resources-unified-index.md


-----


** Git branch organization and history cleanup

(Also see docs/git-history.txt)

On 2025-04-28, created a new orphan branch =main= and removed the =master= branch, to cleanup the git history and remove references to large files (images) that were added to commits and subsequently removed.

The branch =backup-branch= will be kept temporary in case things go wrong.

The new =main= branch starts with a clean history.

Feature branches =wip= contain individual work in progress, intended to be merged/squashed/deleted after they are done, to not bring in unnecessary commits and files to the main branch.

*** Sizes

Size while branch =branch-backup= exists with full history:

#+BEGIN_SRC shell
$ du -sh .git
2.5G    .git

$ du -sh .
4.5G    .

$ git count-objects -vH
count: 11
size: 141.35 KiB
in-pack: 20852
packs: 1
size-pack: 2.39 GiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
#+END_SRC

Size after branch =branch-backup= is deleted, and after running =git gc --prune=now --aggressive= and =git clean -fd=:

#+BEGIN_SRC shell
$ du -sh .git
2.4G    .git

$ du -sh .
4.5G    .

$ git count-objects -vH
count: 0
size: 0 bytes
in-pack: 20852
packs: 1
size-pack: 2.37 GiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes

# Field	Meaning
# count	Number of loose (unpacked) Git objects (commits, trees, blobs, etc.)
# size	Total disk size of loose objects
# in-pack	Number of objects stored inside packfiles (efficient compressed storage)
# packs	Number of packfiles
# size-pack	Total disk size of packfiles
# prune-packable	Number of loose objects that could be packed (but aren't yet)
# garbage	Number of corrupt or incomplete objects
# size-garbage	Total disk size of the garbage
#+END_SRC

*** New process for WIP and ensuring that unnecessary files (like images) are not added to the main git branch

- use new branches "wip-*" for albums/clubs/guides while they are being developed (branching from main branch)
  - no need to push feature branches to github (probably)
  - occassionally rebase/merge from main if/when necessary (e.g. upgrades to main which would be useful for all feature branches to have)
- when work is done and article is published, merge the wip (feature) branch to the main branch, squashing commits so that extra unnecessary files are not preserved in the history
- keeps history of main branch clean
- delete wip (feature) branch when done
